### ISSUE TITLE
Lint throws a t-003 warning for Manual Review: add to se-lint-ignore ?

### ISSUE THREAD

**Issue by drgrigg** [pcrooker/edgar-rice-burroughs_tarzan-of-the-apes#1]
What you have is **correct** (no closing quote at the end of a para if the speech continues). No need to change anything.

However this would be a good candidate for an se-lint-ignore.xml file, [see this bit in the manual](https://standardebooks.org/manual/1.6.2/single-page#2.3). It just stops that particular warning popping up every time you run lint on your project.

It would look something like this, and goes at the root level of the production folder:

```
<?xml version="1.0" encoding="utf-8"?>
<se-lint-ignore>
	<file path="chapter-2.xhtml">
		<ignore>
			<code>t-003</code>
			<reason>The missing closing quote is correct because Black Michael’s speech continues to the next paragraph.</reason>
		</ignore>
	</file>
</se-lint-ignore>
```

**Comment by pcrooker** [comment]
Yes, I checked that out thoroughly and saw the text was correct. Odd that that specific instance was picked up and not the others, of which there are many though the book.

Good to know about the ignore file.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by drgrigg** [comment]
Unfortunately lint now throws another error, 

`Non-typogrified character in <meta property="se:long-description"> element.`

It's the straight quote in "book's", the apostrophe needs to be a curly quote.

**Comment by drgrigg** [comment]
Just run typogrify once again, that fixes it.

**Comment by pcrooker** [comment]
Hi David,

Should have thought about that apostrophe...

OK, so I run se clean, it removes the linefeed that was there after the closing xml tag in se-lint-ignore.xml. Having a final linefeed in linux/unix is normal practice but whatever. Also se clean removes all the 'cosmetic' linefeeds (as in helpful when editing but normally ignored in html) I put in the long description. However, when I run typogrify it puts both lots of linefeeds back in again...??? Which is correct?

thanks, Phil

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by drgrigg** [comment]
Ha! Alex should look at that.

I think it's much more usual to run typogrify late in the production rather than clean, so let's go with whatever typogrify wants to do.

**Comment by pcrooker** [comment]
Now typogrify kept the linefeeds as clean left them. Bah.

Anyway, I've committed and pushed the latest changes.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
