### ISSUE TITLE
Commit marked as [Editorial] which shouldn't be

### ISSUE THREAD

**Issue by drgrigg** [pcrooker/edgar-rice-burroughs_tarzan-of-the-apes#4]
You're going to hate me, but your commit 0911822b07c1a0300fb5c8a3b00fd3defac6fc90 "[Editorial] changed cases in letters, repaired semantics, typography"  shouldn't be marked as "[Editorial]". The changes made all seem to be things like switching the language, removing a class, running typogrify. None of these require being marked as [Editorial].

(The OTHER commits where you've used this tag are fine, leave them)

We reserve the [Editorial] tag for commits where we are _making an editorial **decision** to alter something away from what the page scans show_ . The most obvious such case is where we are modernizing the spelling. Typogrify is a standard routine we run which doesn't fundamentally alter the text. Changes to the language tag is just affecting metadata. Ditto for removing the classes.

You'll probably hate me because removing the [Editorial] tag on this commit message means rebasing the repository, something which personally gives me the willies, but if you're familiar with git you shouldn't have any problems with it. And there are many other producers here who can give you guidance on how to do it.

**Comment by drgrigg** [comment]
@acabal : do we need to make this clearer in the manual?

**Comment by acabal** [comment]
We can probably put an alert about it, akin to the cover art alert, in the step by step guide. Emphasizing to stick to the exact commit messages in the guide, and explaining more about [Editorial]. If you have some free time you can put together a pull request for that.

**Comment by acabal** [comment]
BTW if you just need to change the commit message to remove [Editorial], that's very easy.

**Comment by pcrooker** [comment]
Yes, thanks, I thought that might be the case.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
