### ISSUE TITLE
Make short description in content.opf more generic

### ISSUE THREAD

**Issue by drgrigg** [pcrooker/edgar-rice-burroughs_tarzan-of-the-apes#7]
It's generally our style not to include character names in the short description. Also, "raized" is incorrect spelling.

I would make it something like:

`The origin and early adventures of a man orphaned as a baby and raised by apes in Africa.`

**Comment by pcrooker** [comment]
heh - I'm so used to converting to american spelling...

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
